IpoetryBundle\Entity\IpoetryUserAge:
    type: entity
    table: ipoetry_user_age
    id:
        ipoetryUserAgeId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ipoetry_user_age_id
            generator:
                strategy: IDENTITY
    fields:
        ipoetryUserAge:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ipoetry_user_age
    lifecycleCallbacks: {  }
